### ISSUE TITLE
Requirement Error

### ISSUE THREAD

**Issue by Mrrobi** [monjurkuet/airflow_app#1]
> => [webserver 3/5] COPY requirements.txt /opt/airflow_app/requirements.txt                                        0.0s
>  => [webserver 4/5] RUN apt-get update && apt-get install -y     chromium     chromium-driver                     38.4s
>  => ERROR [webserver 5/5] RUN pip install -r /opt/airflow_app/requirements.txt                                     1.6s
> 
>  [webserver 5/5] RUN pip install -r /opt/airflow_app/requirements.txt:
> 1.046 Collecting pandas==2.2.1 (from -r /opt/airflow_app/requirements.txt (line 1))
> 1.097   Downloading pandas-2.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
> 1.119 ERROR: Could not find a version that satisfies the requirement bs4==4.12.2 (from versions: 0.0.0, 0.0.1, 0.0.2)
> 1.119 ERROR: No matching distribution found for bs4==4.12.2
> 
> failed to solve: process "/bin/bash -o pipefail -o errexit -o nounset -o nolog -c pip install -r /opt/airflow_app/requirements.txt" did not complete successfully: exit code: 1

**Comment by monjurkuet** [comment]
pandas
bs4
selenium
pymongo

use this for requirements.txt  looks like specifying version is causing issue.

**Comment by Mrrobi** [comment]
Didn't you deployed it on your end?

**Comment by monjurkuet** [comment]
Yes I deployed it on my end but I used the requirements file without specifying version. I added the versions later on before but didn't actually check it. It was an oversight on my end.
